version: '2'
services:
  irods-exporter-worker:
    build: docker/
    hostname: irods-exporter-worker
    networks:
      - default
      - corpus_default
      - common_default
    volumes:
      - ./etl:/opt/app
    env_file:
      - ./secrets.cfg    
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      IRODS_HOST: irods.dev7.rit.unimaas.nl
      IRODS_USER: rods
      IRODS_PASS: irods
      DATAVERSE_HOST: https://act.dataverse.nl
      EASY_HOST : https://act.easy.dans.knaw.nl
      DH_MAILER_HOST: mailer
      DH_MAILER_USERNAME: user
      DH_MAILER_PASSWORD: password
      LOG_LEVEL: INFO
      LOGSTASH_TAGS: COLLECTION_WORKER
networks:
  common_default:
    external: true
  corpus_default:
    external: true
