version: '2'
services:
  irods-exporter-worker:
    build: docker/
    networks:
      corpus_default:
        aliases:
          - open-access-worker.dh.local
      common_default:
        aliases:
          - open-access-worker.dh.local
    volumes:
      - ./etl:/opt/app
    env_file:
      - ./secrets.cfg  # Using ONLY DATAVERSE_TOKEN. Can also be added as env var below
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      IRODS_HOST: irods.dh.local
      IRODS_USER: rods
      IRODS_PASS: irods
      DATAVERSE_HOST: https://dataverse.nl
      DH_MAILER_HOST: mailer.dh.local
      DH_MAILER_USERNAME: user
      DH_MAILER_PASSWORD: password
      LOG_LEVEL: INFO
      LOGSTASH_TAGS: OPEN_ACCESS_WORKER
networks:
  common_default:
    external: true
  corpus_default:
    external: true
